### ISSUE TITLE
[Task] PHP 8 compatibility

### ISSUE THREAD

**Issue by andpavlenko** [struzik-vladislav/epp-client#3]
Hi, Vladislav
EPP Client dont't work properly at PHP >=8.0. Time to make modification to compatible for newer PHP >=7.4 with small changes.

`PHP Fatal error:  Declaration of DOMDocument::createElement(string $localName, string $value = "") must be compatible with Struzik\EPPClient\Request\RequestInterface::createElement($name, $value = null) in /home/vagrant/code/my.xosting.devel/xosting/vendor/struzik-vladislav/epp-client/src/Request/AbstractRequest.php on line 0`

php -v

`PHP 8.0.17 (cli) (built: Mar 20 2022 17:04:09) ( NTS )`

**Comment by struzik-vladislav** [comment]
Hi, @andpavlenko !
Thanks for notifying me of the issue. It will be fixed today in a new patch version.

From tomorrow I start working on EPP Client 2. It will be compatible from PHP >=7.4. The new version will be ready within a few weeks. Version 2 will not be backward compatible with version 1.

**Comment by struzik-vladislav** [comment]
Issue resolved in v1.0.1

**Comment by andpavlenko** [comment]
> From tomorrow I start working on EPP Client 2. It will be compatible from PHP >=7.4. The new version will be ready within a few weeks. Version 2 will not be backward compatible with version 1.

@struzik-vladislav Good news! Interesting to see this.
v2 compatible with PHP 8.1, I hope?

**Comment by struzik-vladislav** [comment]
@andpavlenko 
Now I don't see any problems to make it compatible with PHP 7.4-8.1. Perhaps you can advise a free CI to perform tests on different versions of PHP?

**Comment by andpavlenko** [comment]
@struzik-vladislav 
Usual for cool projects its PHPUnit + Travis CI. But simple way it's manual. ;)

**Comment by struzik-vladislav** [comment]
Hi @andpavlenko 
The EPPClient V2 is released. All connections and extensions is updated. You can watch them in the README or suggest section of composer.json.

**Comment by andpavlenko** [comment]
Hi, @struzik-vladislav It's goog work. I will test it a few days.
